---
swagger: "2.0"
info:
  version: "2017-09-28T00:34:41Z"
  title: "AlertAPIGateway"
host: "0m1v7o3czd.execute-api.us-west-2.amazonaws.com"
basePath: "/prod"
schemes:
- "https"
paths:
  /ApiGatewayalert:
    post:
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
